version: "2"

services:
  mongodb-primary:
    image: "bitnami/mongodb:4.2.5"
    container_name: "mongodb-primary"
    ports:
      - "27717:27717"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_PRIMARY_HOSTNAME}
      - MONGODB_PORT_NUMBER=27717
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - "mongodb_master_data:/bitnami"
    networks:
      - replica-docker

  mongodb-secondary:
    image: "bitnami/mongodb:4.2.5"
    container_name: "mongodb-secondary"
    ports:
      - "27718:27718"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PORT_NUMBER=27718
      - MONGODB_PRIMARY_PORT_NUMBER=27717
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_SECONDARY_HOSTNAME}
      - MONGODB_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
    volumes:
      - "mongodb_secondary_data:/bitnami"
    networks:
      - replica-docker

  mongodb-arbiter:
    image: "bitnami/mongodb:4.2.5"
    container_name: "mongodb-arbiter"
    ports:
      - "27720:27720"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PORT_NUMBER=27720
      - MONGODB_PRIMARY_PORT_NUMBER=27717
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_ARBITER_HOSTNAME}
      - MONGODB_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
    volumes:
      - "mongodb_arbiter_data:/bitnami"
    networks:
      - replica-docker

volumes:
  mongodb_master_data:
    driver: local
  mongodb_arbiter_data:
    driver: local
  mongodb_secondary_data:
    driver: local

networks:
  replica-docker:
