version: "2"

services:
  mongodb:
    image: "bitnami/mongodb:5.0"
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_SECONDARY_HOSTNAME}
      - MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_PRIMARY_HOSTNAME}
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=${MONGODB_PORT_NUMBER}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
    ports:
      - "${MONGODB_PORT_NUMBER:-27017}:27017"
    volumes:
      - "mongodb_data:/bitnami"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always

volumes:
  mongodb_data:
    driver: local
